apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-v002
  labels:
    app: backend-v002
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-v002
  template:
    metadata:
      labels:
        app: backend-v002
    spec:
      containers:
      - name: fastapi-server
        image: quay.io/shanand/github-bot:v0.0.2
        imagePullPolicy: Always
        command: ["uvicorn"]
        args: ["backend.api.main:app", "--host", "0.0.0.0", "--port", "8080"]
        ports:
        - containerPort: 8080
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: backend-v002-secrets
              key: OPENAI_API_KEY
        - name: TAVILY_API_KEY
          valueFrom:
            secretKeyRef:
              name: backend-v002-secrets
              key: TAVILY_API_KEY
        - name: GITHUB_MCP_URL
          valueFrom:
            secretKeyRef:
              name: backend-v002-secrets
              key: GITHUB_MCP_URL
        - name: GITHUB_PAT
          valueFrom:
            secretKeyRef:
              name: backend-v002-secrets
              key: GITHUB_PAT
      - name: grpc-server
        image: quay.io/shanand/github-bot:v0.0.2
        imagePullPolicy: Always
        command: ["python"]
        args: ["-m", "backend.grpc.server"]
        ports:
        - containerPort: 50051
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: backend-v002-secrets
              key: OPENAI_API_KEY
        - name: TAVILY_API_KEY
          valueFrom:
            secretKeyRef:
              name: backend-v002-secrets
              key: TAVILY_API_KEY
        - name: GITHUB_MCP_URL
          valueFrom:
            secretKeyRef:
              name: backend-v002-secrets
              key: GITHUB_MCP_URL
        - name: GITHUB_PAT
          valueFrom:
            secretKeyRef:
              name: backend-v002-secrets
              key: GITHUB_PAT
