apiVersion: v1
kind: Service
metadata:
  name: frontend-v002
  labels:
    app: frontend-v002
spec:
  selector:
    app: frontend-v002
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080 
